// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type SubmissionStatus string

const (
	SubmissionStatusQueued    SubmissionStatus = "queued"
	SubmissionStatusRunning   SubmissionStatus = "running"
	SubmissionStatusCompleted SubmissionStatus = "completed"
	SubmissionStatusFailed    SubmissionStatus = "failed"
)

func (e *SubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionStatus(s)
	case string:
		*e = SubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionStatus: %T", src)
	}
	return nil
}

type NullSubmissionStatus struct {
	SubmissionStatus SubmissionStatus `json:"submission_status"`
	Valid            bool             `json:"valid"` // Valid is true if SubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionStatus), nil
}

type Submission struct {
	ID            uuid.UUID        `json:"id"`
	Language      string           `json:"language"`
	Code          string           `json:"code"`
	Stdin         string           `json:"stdin"`
	WebhookUrl    *string          `json:"webhook_url"`
	Status        SubmissionStatus `json:"status"`
	Stdout        *string          `json:"stdout"`
	Stderr        *string          `json:"stderr"`
	ExitCode      *int32           `json:"exit_code"`
	CompileOutput *string          `json:"compile_output"`
	CpuTimeMs     *int64           `json:"cpu_time_ms"`
	WallTimeMs    *int64           `json:"wall_time_ms"`
	MemoryKb      *int64           `json:"memory_kb"`
	TimedOut      bool             `json:"timed_out"`
	OomKilled     bool             `json:"oom_killed"`
	Error         *string          `json:"error"`
	CreatedAt     time.Time        `json:"created_at"`
	StartedAt     *time.Time       `json:"started_at"`
	FinishedAt    *time.Time       `json:"finished_at"`
}
