// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeSubmission = `-- name: CompleteSubmission :one
UPDATE submissions
SET status         = 'completed',
    stdout         = $2,
    stderr         = $3,
    exit_code      = $4,
    compile_output = $5,
    cpu_time_ms    = $6,
    wall_time_ms   = $7,
    memory_kb      = $8,
    timed_out      = $9,
    oom_killed     = $10,
    finished_at    = now()
WHERE id = $1
RETURNING id, language, code, stdin, webhook_url, status, stdout, stderr, exit_code, compile_output, cpu_time_ms, wall_time_ms, memory_kb, timed_out, oom_killed, error, created_at, started_at, finished_at
`

type CompleteSubmissionParams struct {
	ID            uuid.UUID `json:"id"`
	Stdout        *string   `json:"stdout"`
	Stderr        *string   `json:"stderr"`
	ExitCode      *int32    `json:"exit_code"`
	CompileOutput *string   `json:"compile_output"`
	CpuTimeMs     *int64    `json:"cpu_time_ms"`
	WallTimeMs    *int64    `json:"wall_time_ms"`
	MemoryKb      *int64    `json:"memory_kb"`
	TimedOut      bool      `json:"timed_out"`
	OomKilled     bool      `json:"oom_killed"`
}

func (q *Queries) CompleteSubmission(ctx context.Context, arg CompleteSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, completeSubmission,
		arg.ID,
		arg.Stdout,
		arg.Stderr,
		arg.ExitCode,
		arg.CompileOutput,
		arg.CpuTimeMs,
		arg.WallTimeMs,
		arg.MemoryKb,
		arg.TimedOut,
		arg.OomKilled,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.Code,
		&i.Stdin,
		&i.WebhookUrl,
		&i.Status,
		&i.Stdout,
		&i.Stderr,
		&i.ExitCode,
		&i.CompileOutput,
		&i.CpuTimeMs,
		&i.WallTimeMs,
		&i.MemoryKb,
		&i.TimedOut,
		&i.OomKilled,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (id, language, code, stdin, webhook_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, language, code, stdin, webhook_url, status, stdout, stderr, exit_code, compile_output, cpu_time_ms, wall_time_ms, memory_kb, timed_out, oom_killed, error, created_at, started_at, finished_at
`

type CreateSubmissionParams struct {
	ID         uuid.UUID `json:"id"`
	Language   string    `json:"language"`
	Code       string    `json:"code"`
	Stdin      string    `json:"stdin"`
	WebhookUrl *string   `json:"webhook_url"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ID,
		arg.Language,
		arg.Code,
		arg.Stdin,
		arg.WebhookUrl,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.Code,
		&i.Stdin,
		&i.WebhookUrl,
		&i.Status,
		&i.Stdout,
		&i.Stderr,
		&i.ExitCode,
		&i.CompileOutput,
		&i.CpuTimeMs,
		&i.WallTimeMs,
		&i.MemoryKb,
		&i.TimedOut,
		&i.OomKilled,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failSubmission = `-- name: FailSubmission :one
UPDATE submissions
SET status      = 'failed',
    error       = $2,
    finished_at = now()
WHERE id = $1
RETURNING id, language, code, stdin, webhook_url, status, stdout, stderr, exit_code, compile_output, cpu_time_ms, wall_time_ms, memory_kb, timed_out, oom_killed, error, created_at, started_at, finished_at
`

type FailSubmissionParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) FailSubmission(ctx context.Context, arg FailSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, failSubmission, arg.ID, arg.Error)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.Code,
		&i.Stdin,
		&i.WebhookUrl,
		&i.Status,
		&i.Stdout,
		&i.Stderr,
		&i.ExitCode,
		&i.CompileOutput,
		&i.CpuTimeMs,
		&i.WallTimeMs,
		&i.MemoryKb,
		&i.TimedOut,
		&i.OomKilled,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, language, code, stdin, webhook_url, status, stdout, stderr, exit_code, compile_output, cpu_time_ms, wall_time_ms, memory_kb, timed_out, oom_killed, error, created_at, started_at, finished_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.Code,
		&i.Stdin,
		&i.WebhookUrl,
		&i.Status,
		&i.Stdout,
		&i.Stderr,
		&i.ExitCode,
		&i.CompileOutput,
		&i.CpuTimeMs,
		&i.WallTimeMs,
		&i.MemoryKb,
		&i.TimedOut,
		&i.OomKilled,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, language, code, stdin, webhook_url, status, stdout, stderr, exit_code, compile_output, cpu_time_ms, wall_time_ms, memory_kb, timed_out, oom_killed, error, created_at, started_at, finished_at FROM submissions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubmissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.Code,
			&i.Stdin,
			&i.WebhookUrl,
			&i.Status,
			&i.Stdout,
			&i.Stderr,
			&i.ExitCode,
			&i.CompileOutput,
			&i.CpuTimeMs,
			&i.WallTimeMs,
			&i.MemoryKb,
			&i.TimedOut,
			&i.OomKilled,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmissionRunning = `-- name: MarkSubmissionRunning :one
UPDATE submissions
SET status = 'running', started_at = now()
WHERE id = $1
RETURNING id, language, code, stdin, webhook_url, status, stdout, stderr, exit_code, compile_output, cpu_time_ms, wall_time_ms, memory_kb, timed_out, oom_killed, error, created_at, started_at, finished_at
`

func (q *Queries) MarkSubmissionRunning(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionRunning, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.Code,
		&i.Stdin,
		&i.WebhookUrl,
		&i.Status,
		&i.Stdout,
		&i.Stderr,
		&i.ExitCode,
		&i.CompileOutput,
		&i.CpuTimeMs,
		&i.WallTimeMs,
		&i.MemoryKb,
		&i.TimedOut,
		&i.OomKilled,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
